create table COCKTAIL (
  ID UUID PRIMARY KEY,
  ID_DRINK TEXT,
  NAME TEXT,
  INGREDIENTS TEXT
);

create table COCKTAIL_SHOPPING_LIST (
  COCKTAIL_ID  UUID REFERENCES COCKTAIL(ID),
  SHOPPINGLIST_ID UUID REFERENCES SHOPPING_LIST(ID),
  PRIMARY KEY (COCKTAIL_ID,SHOPPINGLIST_ID)
);